@startuml FirebaseAuth
namespace FirebaseAuth {
    class Constant {
        {static} + string ROOT_PATH
    }

    class FirebaseAuth {
        {static} + void Initialize()
    }
}

namespace FirebaseAuth.Config {
    enum ConfigEnvironment {
        Development
        Production
    }

    enum LoadingState {
        WaitingToLoad
        Loading
        Complete
    }

    class FirebaseAuthConfig {
        + OAuthConfig OAuthConfig
    }

    class OAuthConfig {
        + string cliendID
        + string cliendSecret
    }

    interface IConfigProvider {
        + IObservable<LoadingState> OnStateChanged
        + FirebaseAuthConfig Config
    }

    class AddressableConfigProvider implements IConfigProvider {
    }

    LoadingState <-- IConfigProvider
    ConfigEnvironment <-- AddressableConfigProvider
    FirebaseAuthConfig o-- OAuthConfig
}
@enduml